import Image from "next/image";
import styles from "./contact.module.css";

export const metadata = {
  title: "Contact Page",
  description: 'Generated by create next app',
}

const Contact = () => {
  
  const a = Math.random();
  console.log(a);
  
  return (
    <section className={ styles.container }>

      <aside className={ styles.imgContainer }>
        <Image src="/contact.png" alt="" fill className={ styles.image }/>
      </aside>
      <aside className={ styles.formContainer }>
        <div suppressHydrationWarning>{a}</div>
        <form action="" className={ styles.form }>
          <input type="text" placeholder="Name and Surname"/>
          <input type="email" placeholder="Email Address"/>
          <input type="tel" placeholder="Phone Number (Optional)"/>
          <textarea name="" id="" cols="30" rows="10" placeholder="Message"></textarea>
          <button>Send</button>
        </form>
      </aside>

    </section>
  )
}

export default Contact;